--[[
    Copyright (C) 2025 SaKeL

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to juraj.vajda@gmail.com
--]]

core.register_alias('default:water_source', 'mcl_core:water_source')
core.register_alias('default:dirt', 'mcl_core:dirt')
core.register_alias('default:dirt_with_rainforest_litter', 'mcl_core:dirt_with_grass')
core.register_alias('default:dirt_with_snow', 'mcl_core:dirt_with_grass_snow')
core.register_alias('default:dirt_with_coniferous_litter', 'mcl_core:podzol')
core.register_alias('default:dirt_with_grass', 'mcl_core:dirt_with_grass')
core.register_alias('default:stick', 'mcl_core:stick')
core.register_alias('default:paper', 'mcl_core:paper')
core.register_alias('default:book', 'mcl_books:book')
core.register_alias('default:skeleton_key', 'mcl_core:gold_nugget')
core.register_alias('default:flint', 'mcl_core:flint')
core.register_alias('default:obsidian_shard', 'mcl_core:prismarine_shard')
core.register_alias('default:clay_brick', 'mcl_core:brick')
core.register_alias('default:mese_crystal_fragment', 'mcl_amethyst:amethyst_shard')
-- Ingots
core.register_alias('default:gold_ingot', 'mcl_core:gold_ingot')
core.register_alias('default:bronze_ingot', 'mcl_copper:copper_ingot')
core.register_alias('default:tin_ingot', 'mcl_core:iron_ingot')
core.register_alias('default:copper_ingot', 'mcl_copper:copper_ingot')
core.register_alias('default:steel_ingot', 'mcl_core:iron_ingot')
core.register_alias('default:coal_lump', 'mcl_core:coal_lump')
core.register_alias('default:gold_lump', 'mcl_core:gold_nugget')

-- Tools
core.register_alias('default:pick_stone', 'mcl_tools:pick_stone')
core.register_alias('default:pick_bronze', 'mcl_tools:pick_gold')
core.register_alias('default:pick_steel', 'mcl_tools:pick_iron')
core.register_alias('default:shovel_stone', 'mcl_tools:shovel_stone')
core.register_alias('default:shovel_bronze', 'mcl_tools:shovel_gold')
core.register_alias('default:shovel_steel', 'mcl_tools:shovel_iron')
core.register_alias('default:axe_stone', 'mcl_tools:axe_stone')
core.register_alias('default:axe_bronze', 'mcl_tools:axe_gold')
core.register_alias('default:axe_steel', 'mcl_tools:axe_iron')
core.register_alias('default:sword_stone', 'mcl_tools:sword_stone')
core.register_alias('default:sword_bronze', 'mcl_tools:sword_gold')
core.register_alias('default:sword_steel', 'mcl_tools:sword_iron')
-- Items / Nodes
core.register_alias('default:bookshelf', 'mcl_books:bookshelf')
core.register_alias('default:sign_wall_wood', 'mcl_signs:wall_sign')
core.register_alias('default:ladder_wood', 'mcl_core:ladder')
core.register_alias('default:ladder_steel', 'mcl_core:ladder')
core.register_alias('default:glass', 'mcl_core:glass')
core.register_alias('default:obsidian_glass', 'mcl_core:glass')
-- Trees
core.register_alias('default:tree', 'mcl_core:tree')
core.register_alias('default:jungletree', 'mcl_core:jungletree')
core.register_alias('default:pine_tree', 'mcl_core:sprucetree')
core.register_alias('default:cactus', 'mcl_core:cactus')
core.register_alias('default:large_cactus_seedling', 'mcl_core:cactus')
core.register_alias('default:papyrus', 'mcl_core:reeds')
core.register_alias('default:junglegrass', 'mcl_flowers:double_grass')
core.register_alias('default:blueberry_bush_sapling', 'mcl_flowers:rose_bush')
core.register_alias('default:sapling', 'mcl_core:sapling')
core.register_alias('default:junglesapling', 'mcl_core:junglesapling')
core.register_alias('default:pine_sapling', 'mcl_core:sprucesapling')
core.register_alias('default:acacia_sapling', 'mcl_core:acaciasapling')
core.register_alias('default:aspen_sapling', 'mcl_core:birchsapling')

core.register_alias('default:clay_lump', 'mcl_core:clay_lump')
core.register_alias('default:tin_lump', 'mcl_raw_ores:raw_gold')
core.register_alias('default:copper_lump', 'mcl_copper:raw_copper')
core.register_alias('default:iron_lump', 'mcl_raw_ores:raw_iron')
core.register_alias('default:coalblock', 'mcl_core:coalblock')
core.register_alias('default:steelblock', 'mcl_core:ironblock')
core.register_alias('default:copperblock', 'mcl_copper:block')
core.register_alias('default:tinblock', 'mcl_core:goldblock')
core.register_alias('default:bronzeblock', 'mcl_copper:block')
core.register_alias('default:mese', 'mesecons_torch:redstoneblock')
core.register_alias('default:meselamp', 'mesecons_lightstone:lightstone_off')
core.register_alias('default:obsidian', 'mcl_core:obsidian')
core.register_alias('default:mese_crystal', 'mcl_ocean:prismarine_crystals')
core.register_alias('default:diamond', 'mcl_core:diamond')
core.register_alias('default:pick_mese', 'mcl_tools:pick_diamond')
core.register_alias('default:shovel_mese', 'mcl_tools:shovel_diamond')
core.register_alias('default:axe_mese', 'mcl_tools:axe_diamond')
core.register_alias('default:sword_mese', 'mcl_tools:sword_diamond')

core.register_alias('default:snowblock', 'mcl_core:snowblock')
core.register_alias('default:ice', 'mcl_core:ice')
core.register_alias('default:torch', 'mcl_torches:torch')
core.register_alias('default:cobble', 'mcl_core:cobble')
core.register_alias('default:chest', 'mcl_chests:chest')
core.register_alias('default:snow', 'mcl_core:snow')
core.register_alias('default:stone', 'mcl_core:stone')
core.register_alias('default:sand', 'mcl_core:sand')
core.register_alias('default:gravel', 'mcl_core:gravel')
core.register_alias('default:stone_with_coal', 'mcl_core:stone_with_coal')
core.register_alias('default:stone_with_iron', 'mcl_core:stone_with_iron')
core.register_alias('default:stone_with_tin', 'mcl_core:stone_with_copper')
core.register_alias('default:stone_with_gold', 'mcl_core:stone_with_gold')
core.register_alias('default:stone_with_mese', 'mcl_core:stone_with_redstone')
core.register_alias('default:stone_with_diamond', 'mcl_core:stone_with_diamond')
core.register_alias('default:lava_source', 'mcl_core:lava_source')
core.register_alias('default:mossycobble', 'mcl_core:mossycobble')
core.register_alias('default:clay', 'mcl_colorblocks:hardened_clay')
core.register_alias('default:dry_dirt_with_dry_grass', 'mcl_core:dirt_with_grass')
core.register_alias('default:dry_dirt', 'mcl_core:coarse_dirt')
core.register_alias('default:coral_skeleton', 'mcl_core:bone_block')
core.register_alias('default:coral_orange', 'mcl_ocean:tube_coral_block')
core.register_alias('default:coral_brown', 'mcl_ocean:brain_coral_block')
core.register_alias('default:lava_flowing', 'mcl_core:lava_flowing')
core.register_alias('stairs:slab_cursed_brick_with_growth', 'mcl_stairs:slab_cursed_brick_with_growth')
core.register_alias('default:fence_wood', 'mcl_fences:fence')
core.register_alias('default:torch_wall', 'mcl_torches:torch_wall')
core.register_alias('default:wood', 'mcl_core:wood')
core.register_alias('default:junglewood', 'mcl_core:junglewood')
core.register_alias('default:pine_wood', 'mcl_core:sprucewood')
core.register_alias('default:mese_post_light_pine_wood', 'mcl_torches:torch')
core.register_alias_force('default:acacia_tree', 'mcl_core:acaciatree')
core.register_alias('default:dry_grass_4', 'mcl_core:deadbush')
core.register_alias('default:dry_grass_2', 'mcl_core:deadbush')
core.register_alias('default:dry_shrub', 'mcl_core:deadbush')
core.register_alias('default:stonebrick', 'mcl_core:stonebrick')
core.register_alias('default:jungleleaves', 'mcl_core:jungleleaves')
core.register_alias('default:torch_ceiling', 'mcl_torches:torch_wall')
core.register_alias('default:goldblock', 'mcl_core:goldblock')
core.register_alias('stairs:stair_junglewood', 'mcl_stairs:stair_junglewood')
core.register_alias('stairs:slab_junglewood', 'mcl_stairs:slab_junglewood')
core.register_alias('stairs:slab_dry_wood', 'mcl_stairs:slab_dry_wood')
core.register_alias('stairs:stair_dry_wood', 'mcl_stairs:stair_dry_wood')
core.register_alias('stairs:stair_wood', 'mcl_stairs:stair_wood')
core.register_alias('stairs:slab_stonebrick', 'mcl_stairs:slab_stonebrick')
core.register_alias('stairs:stair_inner_wood', 'mcl_stairs:stair_wood_inner')
core.register_alias('stairs:stair_outer_stonebrick', 'mcl_stairs:stair_stonebrick_outer')
core.register_alias('stairs:stair_stonebrick', 'mcl_stairs:stair_stonebrick')
core.register_alias('stairs:stair_mossycobble', 'mcl_stairs:stair_mossycobble')

core.register_alias('walls:cobble', 'mcl_walls:cobble')
core.register_alias('xpanes:trapdoor_steel_bar', 'mcl_doors:iron_trapdoor')
core.register_alias('doors:trapdoor_open', 'mcl_doors:trapdoor_open')
core.register_alias('doors:trapdoor', 'mcl_doors:trapdoor')
core.register_alias('doors:door_wood_a', 'mcl_doors:wooden_door')
core.register_alias('doors:hidden', 'air')

-- Dye
core.register_alias('dye:brown', 'mcl_dye:brown')
core.register_alias('dye:black', 'mcl:dye:black')
core.register_alias('dye:blue', 'mcl:dye:blue')
core.register_alias('dye:cyan', 'mcl:dye:cyan')
core.register_alias('dye:dark_grey', 'mcl:dye:dark_grey')
core.register_alias('dye:grey', 'mcl:dye:grey')
core.register_alias('dye:dark_green', 'mcl:dye:dark_green')
core.register_alias('dye:green', 'mcl:dye:green')
core.register_alias('dye:magenta', 'mcl:dye:magenta')
core.register_alias('dye:orange', 'mcl:dye:orange')
core.register_alias('dye:pink', 'mcl:dye:pink')
core.register_alias('dye:violet', 'mcl:dye:violet')
core.register_alias('dye:red', 'mcl:dye:red')
core.register_alias('dye:white', 'mcl:dye:white')
core.register_alias('dye:yellow', 'mcl:dye:yellow')
core.register_alias('default:sand_with_kelp', 'mcl_ocean:kelp')
